In [28]:
colors = ['White','Gray','Blue']
storages = [64,128,256]
phones = [(color, storage) for color in colors for storage in storages]
phones

[('White', 64),
 ('White', 128),
 ('White', 256),
 ('Gray', 64),
 ('Gray', 128),
 ('Gray', 256),
 ('Blue', 64),
 ('Blue', 128),
 ('Blue', 256)]

In [19]:
check_up = [('Rohan',124,98),('John',130,95),('prasanna',110,98),('felix',120,102)]
print('{:15} | {:15} | {:15}'.format('Patient Name', 'Blood Pressure', 'Temperature'))
f = '{:15} | {:15} | {:15}'
for (name,blood_pressure,temperature) in check_up: 
    print(f.format(name, blood_pressure, temperature))

Patient Name    | Blood Pressure  | Temperature    
Rohan           |             124 |              98
John            |             130 |              95
prasanna        |             110 |              98
felix           |             120 |             102


In [20]:
check_up = [] 
cdata = input("Please enter data about the patient:\n") 
while(cdata != ''): 
    check_up.append(tuple(cdata.split(","))) 
    cdata = input() 
print('{:15} | {:15} | {:15}'.format('Patient Name', 'Blood Pressure', 'Temperature'))
f = '{:15} | {:15} | {:15}'
for (name,blood_pressure,temperature) in check_up: 
    print(f.format(name, blood_pressure, temperature))

Patient Name    | Blood Pressure  | Temperature    
John            | 120             | 98             
Rahul           | 110             | 98             
venket          | 143             | 97             


In [21]:
print("Holidays:")
holidays = [('Gandhi Jayanti','2nd october'),('Ayudha Pooja','4th October'),('Diwali','24th and 25th October'),('Christmas Day','25th December')]
print('{:15} | {:15}'.format('Festival', 'Date'))
f = '{:15} | {:15}'
for (festival,date) in holidays: 
    print(f.format(festival, date))

Holidays:
Festival        | Date           
Gandhi Jayanti  | 2nd october    
Ayudha Pooja    | 4th October    
Diwali          | 24th and 25th October
Christmas Day   | 25th December  


In [12]:
from collections import namedtuple
holiday = namedtuple('holiday','Festival Date')
hd1 = holiday('New year','1st of January 2023')

In [13]:
hd1

holiday(Festival='New year', Date='1st of January 2023')

In [21]:
def main():
    names = []
    name = input("Enter list of names:")
    names= name.split(',')
    print("sorting name in alphabatical order")
    print(sorted(names))
    print("sorting names in reverse alphabatical order:")
    print(sorted(names, reverse = True))
    print("sorting names according to the length of the names ")
    print(sorted(names, key = len, reverse = False))
    print("sorting names accordint to the length of the names in reverse order")
    print(sorted(names, key = len, reverse=True))
    
if __name__ == "__main__":
    main()

sorting name in alphabatical order
['Aravind', 'Aswin', 'Rahul', 'Rakesh', 'liam']
sorting names in reverse alphabatical order:
['liam', 'Rakesh', 'Rahul', 'Aswin', 'Aravind']
sorting names according to the length of the names 
['liam', 'Rahul', 'Aswin', 'Rakesh', 'Aravind']
sorting names accordint to the length of the names in reverse order
['Aravind', 'Rakesh', 'Rahul', 'Aswin', 'liam']


In [38]:
def main():
    list_of_tupels = [] 
    values = input("Datas:\n") 
    while(values != ''): 
        list_of_tupels.append(tuple(values.split(","))) 
        values = input()
    print(sorted(list_of_tupels,key =lambda x: x[1]))

if __name__ == '__main__':
    main()

[('5', '1'), ('1', '2'), ('3', '6')]


In [28]:
import bisect

def get_grade(marks):
    cutoffs  = [60, 70, 80 , 90]
    grades = 'FDCBA'
    i= bisect.bisect_right(cutoffs,marks)
    return grades[i]

def main():
    name = input("Name: ")
    marks = int(input("Marks: "))
    print(f"Grade that {name} has got is {get_grade(marks)}")
        
if __name__ == "__main__":
    main()  

Grade that Aswin has got is A


In [34]:
import bisect

def insert_mark(a,mark):
    bisect.insort_right(a,mark)
    return a 

def avg(a):
    sum = 0
    for mk in a :
        sum = sum + mk 
    average = sum/len(a)
    return average

def main():
    a = [70,75,69,80,91,82,91,74] 
    mark = int(input("enter the mark:"))
    print(a)
    print(f"class average before adding a mark {avg(a)}")
    a = insert_mark(a,mark)
    print(a)
    print(f"class average after adding a mark {avg(a)}")
        
if __name__ == "__main__":
    main()  

[70, 75, 69, 80, 91, 82, 91, 74]
class average before adding a mark 79.0
[70, 75, 69, 80, 89, 91, 82, 91, 74]
class average after adding a mark 80.11111111111111


In [43]:
import array

def id_checker(id_no,n):
    for e in id_no:
        if e == n:
            return f"{n} ID is vaild"
    return f"{n} ID is not valid"
        
def main():
    id_no = array.array('i',[1293,3232,2123,8290,2194,2211,2325,2765,3257])
    n = int(input("Enter you Id No:"))
    print(id_checker(id_no,n))

if __name__ == "__main__":
    main()

3232 ID is vaild


In [5]:
import numpy

def id_checker(id_no,n):
    for e in id_no:
        if e == n:
            return f"{n} ID is vaild"
    return f"{n} ID is not valid"
        
def main():
    id_no = numpy.array([1293,3232,2123,8290,2194,2211,2325,2765,3257])
    n = int(input("Enter you Id No:"))
    print(id_checker(id_no,n))

if __name__ == "__main__":
    main()


1293 ID is vaild


In [23]:
import numpy

def add_m(m1,m2):
    print(f"{m1}\n +")
    print(f"{m2}\n =")
    m3 = numpy.add(m1,m2)
    print(m3)

def sub_m(m1,m2):
    print(f"{m1}\n -")
    print(f"{m2}\n =")
    m3 = numpy.subtract(m1,m2)
    print(m3)

def multi_m(m1,m2):
    print(f"{m1}\n *")
    print(f"{m2}\n =")
    m3 = numpy.multiply(m1,m2)
    print(m3)
    
def main():  
    row1 = int(input("Enter no of rows in first matrix: "))
    col1 = int(input("Enter no of column in first matrix: "))
    row2 = int(input("Enter no of rows in second matrix: "))
    col2 = int(input("Enter no of column in second matrix: "))
    el1 = list(map(int,input("enter matrix 1 elements: ").split()))
    el2 = list(map(int,input("enter matrix 2 elements: ").split()))
    m1 = numpy.array(el1).reshape(row1,col1)
    m2 = numpy.array(el2).reshape(row2,col2)
    i = int(input("1.Addition\n2.Subraction\n3.Multiplication\n Choose your option: "))
    if i == 1:
        if row1 == row2 and col1 == col2:
            add_m(m1,m2)
        else:
            print("matrix addition not possible")
    elif i == 2:
        if row1 == row2 and col1 == col2:
            sub_m(m1,m2)
        else:
            print("matrix subraction not possible")
    elif i == 3:
        if col1 == row2:
            multi_m(m1,m2)
        else:
            print("matrix multiplication not possible")
    else:
        print("option not found")        
    

if __name__ == "__main__":
    main()


[[1 2]
 [3 4]]
 *
[[0 9]
 [8 7]]
 =
[[ 0 18]
 [24 28]]


In [34]:
import numpy

def add_m(m1,m2):
    print(f"{m1}\n +")
    print(f"{m2}\n =")
    m3 = numpy.add(m1,m2)
    print(m3)

def sub_m(m1,m2):
    print(f"{m1}\n -")
    print(f"{m2}\n =")
    m3 = numpy.subtract(m1,m2)
    print(m3)

def multi_m(m1,m2):
    print(f"{m1}\n *")
    print(f"{m2}\n =")
    m3 = numpy.multiply(m1,m2)
    print(m3)
    
def main():  
    row1 = int(input("Enter no of rows in first matrix: "))
    col1 = int(input("Enter no of column in first matrix: "))
    row2 = int(input("Enter no of rows in second matrix: "))
    col2 = int(input("Enter no of column in second matrix: "))
    el1 = list(map(int,input("enter matrix 1 elements: ").split()))
    el2 = list(map(int,input("enter matrix 2 elements: ").split()))
    m1 = numpy.array(el1).reshape(row1,col1)
    m2 = numpy.array(el2).reshape(row2,col2)
    i = int(input("1.Addition\n2.Subraction\n3.Multiplication\n Choose your option: "))
    if i == 1:
        if row1 == row2 and col1 == col2:
            add_m(m1,m2)
        else:
            print("matrix addition not possible")
    elif i == 2:
        if row1 == row2 and col1 == col2:
            sub_m(m1,m2)
        else:
            print("matrix subraction not possible")
    elif i == 3:
        if col1 == row2:
            multi_m(m1,m2)
        else:
            print("matrix multiplication not possible")
    else:
        print("option not found")        
    

if __name__ == "__main__":
    main()


[[1 2]
 [3 4]]
 +
[[0 9]
 [8 7]]
 =
[[ 1 11]
 [11 11]]


In [35]:
import numpy

def add_m(m1,m2):
    print(f"{m1}\n +")
    print(f"{m2}\n =")
    m3 = numpy.add(m1,m2)
    print(m3)

def sub_m(m1,m2):
    print(f"{m1}\n -")
    print(f"{m2}\n =")
    m3 = numpy.subtract(m1,m2)
    print(m3)

def multi_m(m1,m2):
    print(f"{m1}\n *")
    print(f"{m2}\n =")
    m3 = numpy.multiply(m1,m2)
    print(m3)
    
def main():  
    row1 = int(input("Enter no of rows in first matrix: "))
    col1 = int(input("Enter no of column in first matrix: "))
    row2 = int(input("Enter no of rows in second matrix: "))
    col2 = int(input("Enter no of column in second matrix: "))
    el1 = list(map(int,input("enter matrix 1 elements: ").split()))
    el2 = list(map(int,input("enter matrix 2 elements: ").split()))
    m1 = numpy.array(el1).reshape(row1,col1)
    m2 = numpy.array(el2).reshape(row2,col2)
    i = int(input("1.Addition\n2.Subraction\n3.Multiplication\n Choose your option: "))
    if i == 1:
        if row1 == row2 and col1 == col2:
            add_m(m1,m2)
        else:
            print("matrix addition not possible")
    elif i == 2:
        if row1 == row2 and col1 == col2:
            sub_m(m1,m2)
        else:
            print("matrix subraction not possible")
    elif i == 3:
        if col1 == row2:
            multi_m(m1,m2)
        else:
            print("matrix multiplication not possible")
    else:
        print("option not found")        
    

if __name__ == "__main__":
    main()


[[1 2]
 [3 4]]
 -
[[0 9]
 [8 7]]
 =
[[ 1 -7]
 [-5 -3]]


In [33]:
from collections import deque

months = deque(["Mar","Apr","May","Jun","July","Aug","Sept","Oct","Nov","Jan","Wed"],maxlen=12)
print(months)
months.appendleft("Feb")
print(months)
months.remove("Wed")
print(months)
months.rotate(1)
print(months)
months.append("Dec")
print(months)

deque(['Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Jan', 'Wed'], maxlen=12)
deque(['Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Jan', 'Wed'], maxlen=12)
deque(['Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Jan'], maxlen=12)
deque(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sept', 'Oct', 'Nov'], maxlen=12)
deque(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'], maxlen=12)
